version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 0.0.0.0:27017:27017
    volumes:
      - data-volume:/data

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    depends_on:
      - mongodb
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 0.0.0.0:8081:8081

volumes:
  data-volume: {}

networks:
  default:
    name: mongodb_network
